### ISSUE TITLE
Admin apporval addition

### ISSUE THREAD

**Issue by adeora7** [CosmicCoder96/php-uploader#1]
Hey, could you add the admin approval part ASAP. Also add LDAP authentication and when you are done tell me, we will setup the new advanced FTP.

**Comment by abhinavk96** [comment]
Adding it today.

**Comment by abhinavk96** [comment]
I'm making separate upload files for admin so that it is easier to change the admin at a farther point in time.

**Comment by abhinavk96** [comment]
I have added the admin approval.
